services:
  mongodb:
    image: mongo:7
    container_name: swccy-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - swccy_mongo_data:/data/db
  mongo-express:
    image: mongo-express:1.0.2
    container_name: swccy-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    depends_on:
      - mongodb
volumes:
  swccy_mongo_data:
